-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 07:37:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clothx_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clothx_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clothx_db` DEFAULT CHARACTER SET utf8 ;
USE `clothx_db` ;

-- -----------------------------------------------------
-- Table `clothx_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothx_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `category_id` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`)
   KEY `category_id` (`category_id`),
  CONSTRAINT `products_fk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)
  ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clothx_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothx_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `users_fk_1` FOREIGN KEY (`category_id`) REFERENCES `users_categories` (`id`)
  ) ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `clothx_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothx_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;